const quote = document.querySelector(".quote");
const person = document.querySelector(".person");

// Generated by ChatGPT
const motivationalQuotes = [
    { q: "The only way to do great work is to love what you do.", p: "Steve Jobs" },
    { q: "Believe you can and you're halfway there.", p: "Theodore Roosevelt" },
    { q: "Don't watch the clock; do what it does. Keep going.", p: "Sam Levenson" },
    { q: "Success is not final, failure is not fatal: It is the courage to continue that counts.", p: "Winston Churchill" },
    { q: "The only limit to our realization of tomorrow will be our doubts of today.", p: "Franklin D. Roosevelt" },
    { q: "Your time is limited, don't waste it living someone else's life.", p: "Steve Jobs" },
    { q: "The future belongs to those who believe in the beauty of their dreams.", p: "Eleanor Roosevelt" },
    { q: "It always seems impossible until it's done.", p: "Nelson Mandela" },
    { q: "Success is stumbling from failure to failure with no loss of enthusiasm.", p: "Winston Churchill" },
    { q: "If you want to lift yourself up, lift up someone else.", p: "Booker T. Washington" },
    { q: "The only place where success comes before work is in the dictionary.", p: "Vidal Sassoon" },
    { q: "You miss 100% of the shots you don't take.", p: "Wayne Gretzky" },
    { q: "It's not whether you get knocked down, it's whether you get up.", p: "Vince Lombardi" },
    { q: "The only person you are destined to become is the person you decide to be.", p: "Ralph Waldo Emerson" },
    { q: "The only limit to our realization of tomorrow will be our doubts of today.", p: "Franklin D. Roosevelt" },
    { q: "Success is not in what you have, but who you are.", p: "Bo Bennett" },
    { q: "You are never too old to set another goal or to dream a new dream.", p: "C.S. Lewis" },
    { q: "Success usually comes to those who are too busy to be looking for it.", p: "Henry David Thoreau" },
    { q: "The best way to predict the future is to create it.", p: "Peter Drucker" },
    { q: "Your attitude, not your aptitude, will determine your altitude.", p: "Zig Ziglar" },
  ];

const arrLen = motivationalQuotes.length;

const button = document.querySelector("#nQuote");
button.addEventListener("click", () => {
    const i = Math.floor(Math.random() * arrLen);
    quote.innerText = motivationalQuotes[i].q;
    person.innerText = motivationalQuotes[i].p;
});

const tweet = document.querySelector("#tweet");
tweet.addEventListener("click", () => {
    const tweetText = `${quote.innerText}\n- ${person.innerText}`;
    window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(tweetText));
});
  